// Шаг автоприсадки: полки.
import type { Part } from '../part';
import { getExpectedSectionSupportPartId, resolveExplicitShelfSupport, countOpsBySource, isValidShelfSupportAdjacency, SHELF_JOINERY_REBUILD_STAGE, hasMirroredHorizontalJoint, getStaggeredJointRules, tagShelfAutoGeneratedOps, appendOps } from './core';
import { findSectionSupport, resolveShelfSideJoinery, createShelfSideJoineryOps } from './horizontal';
import { createEmptySideJoinery } from '../joinery';
import type { GroupJoineryContext } from './apply';

/** Полки: к стойкам секции по своему крепежу или на полкодержатели. */
export function applyShelfJoinery(ctx: GroupJoineryContext) {
  const { groupParts, leftSide, partitionsByX, previousParts, resolvedTiers, rightSide, rules, shelfDebugDecisions, updates } = ctx;
  groupParts
    .filter((part) => part.meta?.role === 'shelf' && part.meta?.sourceId)
    .forEach((shelfPart) => {
      const tier = resolvedTiers.find((item) => item.resolved.shelvesBySection.size > 0 && [...item.resolved.shelvesBySection.values()].flat().some((shelf) => shelf.id === shelfPart.meta?.sourceId));
      const section = tier?.resolved.leafSections.find((item) => (tier.resolved.shelvesBySection.get(item.id) ?? []).some((shelf) => shelf.id === shelfPart.meta?.sourceId));
      if (!section) return;
      const partitionsByX = new Map<string, Part>();
      tier?.resolved.partitions.forEach((partition) => {
        const supportPart = groupParts.find((part) => part.meta?.role === 'partition' && part.meta?.sourceId === partition.id);
        if (supportPart) partitionsByX.set(partition.x.toFixed(3), supportPart);
      });
      const expectedLeftSupportPartId = getExpectedSectionSupportPartId(section, 'left', leftSide, rightSide, partitionsByX);
      const expectedRightSupportPartId = getExpectedSectionSupportPartId(section, 'right', leftSide, rightSide, partitionsByX);
      const fallbackLeftSupport = findSectionSupport(groupParts, section, 'left', partitionsByX);
      const fallbackRightSupport = findSectionSupport(groupParts, section, 'right', partitionsByX);
      const explicitLeftSupport = resolveExplicitShelfSupport(groupParts, shelfPart, 'left');
      const explicitRightSupport = resolveExplicitShelfSupport(groupParts, shelfPart, 'right');
      const leftSupport = explicitLeftSupport ?? fallbackLeftSupport;
      const rightSupport = explicitRightSupport ?? fallbackRightSupport;
      const joinery = shelfPart.meta?.joinery ?? createEmptySideJoinery();
      const leftDecision = resolveShelfSideJoinery(shelfPart, section.id, 'left', joinery.left, leftSupport);
      const rightDecision = resolveShelfSideJoinery(shelfPart, section.id, 'right', joinery.right, rightSupport);

      [leftDecision, rightDecision].forEach((decision) => {
        const removedOldOps = decision.sourceKey ? countOpsBySource(previousParts, decision.sourceKey) : 0;
        const expectedSupportPartId = decision.side === 'left' ? expectedLeftSupportPartId : expectedRightSupportPartId;
        const explicitSupportPartId = decision.side === 'left' ? shelfPart.meta?.leftSupportPartId : shelfPart.meta?.rightSupportPartId;
        const hasExplicitSupport = Boolean(explicitSupportPartId);
        const explicitSupportMatchesSection = explicitSupportPartId && expectedSupportPartId
          ? explicitSupportPartId === expectedSupportPartId
          : true;
        const isJoineryAllowed =
          decision.joinery === 'none'
          || decision.joinery === 'confirmat'
          || decision.joinery === 'minifix-dowel'
          || decision.joinery === 'rafix'
          || decision.joinery === 'shelf_pin';
        const adjacencyValid = decision.support
          ? isValidShelfSupportAdjacency(shelfPart, decision.support)
          : false;

        if (!isJoineryAllowed) {
          console.warn('[shelf-joinery-debug][joinery-disabled-in-stage]', {
            stage: SHELF_JOINERY_REBUILD_STAGE,
            shelfId: decision.shelfId,
            parentSectionId: decision.parentSectionId,
            side: decision.side,
            joinery: decision.joinery,
          });
        }

        if (decision.joinery !== 'none' && !hasExplicitSupport) {
          console.warn('[shelf-joinery-debug][missing-explicit-shelf-support]', {
            stage: SHELF_JOINERY_REBUILD_STAGE,
            shelfId: decision.shelfId,
            parentSectionId: decision.parentSectionId,
            side: decision.side,
            joinery: decision.joinery,
            expectedSupportPartId,
          });
        }
        if (decision.joinery !== 'none' && hasExplicitSupport && expectedSupportPartId && !explicitSupportMatchesSection) {
          console.warn('[shelf-joinery-debug][support-not-in-parent-section]', {
            stage: SHELF_JOINERY_REBUILD_STAGE,
            shelfId: decision.shelfId,
            parentSectionId: decision.parentSectionId,
            side: decision.side,
            joinery: decision.joinery,
            supportPartId: decision.supportPartId,
            expectedSupportPartId,
          });
        }

        if (!decision.support || decision.joinery === 'none' || !isJoineryAllowed || !adjacencyValid) {
          if (decision.joinery !== 'none' && !decision.support) {
            console.warn('[shelf-joinery-debug][no-support]', {
              stage: SHELF_JOINERY_REBUILD_STAGE,
              shelfId: decision.shelfId,
              parentSectionId: decision.parentSectionId,
              side: decision.side,
              joinery: decision.joinery,
              sourceKey: decision.sourceKey,
            });
          }
          if (decision.joinery !== 'none' && decision.support && !adjacencyValid && explicitSupportMatchesSection) {
            console.warn('[shelf-joinery-debug][invalid-adjacency]', {
              shelfId: decision.shelfId,
              parentSectionId: decision.parentSectionId,
              side: decision.side,
              joinery: decision.joinery,
              supportPartId: decision.supportPartId,
              supportPartType: decision.supportPartType,
              sourceKey: decision.sourceKey,
            });
          }
          shelfDebugDecisions.push({
            ...decision,
            generatedOps: 0,
            removedOldOps,
            finalStoredOps: 0,
            renderedMarkers: 0,
            adjacencyValid,
          });
          return;
        }
        const shelfRules = decision.side === 'left' && hasMirroredHorizontalJoint(groupParts, shelfPart, decision.support)
          ? getStaggeredJointRules(shelfPart, rules)
          : rules;
        const ops = createShelfSideJoineryOps(shelfPart, decision.support, decision.side, decision.joinery, shelfRules);
        const taggedHorizontalOps = tagShelfAutoGeneratedOps(ops.horizontalOps, decision, shelfPart);
        const taggedSupportOps = tagShelfAutoGeneratedOps(ops.supportOps, decision, decision.support.supportPart);
        appendOps(updates, shelfPart.id, taggedHorizontalOps);
        appendOps(updates, decision.support.supportPart.id, taggedSupportOps);
        shelfDebugDecisions.push({
          ...decision,
          generatedOps: taggedHorizontalOps.length + taggedSupportOps.length,
          removedOldOps,
          finalStoredOps: 0,
          renderedMarkers: 0,
          adjacencyValid,
        });
      });
    });
}
