// Общее для автоприсадки: правила, метки источников, опоры, привязки и отступы крепежа.
import type { Part, PartFace } from '../part';
import { type JoineryType, createEmptySideJoinery } from '../joinery';
import { type DrillOperation, type AutoGeneratedDrillMeta, createDrillOperation, getFaceAxis } from '../drill';
import type { CabinetSection } from '../cabinet-layout';
import { getFacePointWorld } from '../face-coords';

export type AutoJointRuleDraft = {
  frontOffset: number;
  backOffset: number;
  shelfPinDiameter: number;
  camDowelSpacing: number;
  /** Задан шагом сборки для корпуса с накладной ХДФ: крепёж по глубине отступает от задней кромки дальше. */
  jointBackReserve?: number;
  /** Задан шагом сборки для корпуса на ножках: у дна передняя пара — один конфирмат (там отверстие под ножку). */
  jointBottomFrontSingle?: boolean;
};

export type SectionSupport = {
  supportPart: Part;
  sectionSide: 'left' | 'right';
  supportFace: PartFace;
};

export type ResolvedShelfSideJoinery = {
  shelfId: string;
  parentSectionId: string | null;
  side: 'left' | 'right';
  joinery: JoineryType;
  supportPartId: string | null;
  supportPartType: string | null;
  support: SectionSupport | null;
  resolver: 'section-boundary';
  generator: 'shelf-side-generator';
  sourceKey: string | null;
};

export type ShelfSidePipelineStat = ResolvedShelfSideJoinery & {
  generatedOps: number;
  removedOldOps: number;
  finalStoredOps: number;
  renderedMarkers: number;
  adjacencyValid: boolean;
};

export const SHELF_JOINERY_REBUILD_STAGE = 'restored-v2';

type JoineryDebugAnchor = {
  x: number;
  y: number;
};

export type WorldPoint = {
  x: number;
  y: number;
  z: number;
};

const GENERATED_SOURCE_PREFIX = 'generated-joinery:';
export const camCenterOffsetFromEdge = 34;
export const shelfPinFlexibleStep = 50;
export const APRON_SIDE_Y_SHIFT = 16;
export const APRON_PARTITION_CENTER_SHIFT = 8;
const PARTITION_BACK_SHIFT = 16;
export const CONFIRMAT_THREAD_DIAMETER = 5;
export const CONFIRMAT_THREAD_DEPTH = 50;
export const CONFIRMAT_HEAD_DIAMETER = 8;
export const CONFIRMAT_HEAD_DEPTH = 16;
export const MINIFIX_CONNECTOR_CHANNEL_HOLE_DIAMETER = 8;
// Крепёж в торце детали — по эталону Базиса (26163). В паре наружу идёт шток минификса,
// внутрь — шкант; глубины взяты из выгрузки, по ней реально собирают.
export const MINIFIX_BOLT_DIAMETER = 8;
export const MINIFIX_BOLT_DEPTH = 34;
export const EDGE_DOWEL_DIAMETER = 8;
export const EDGE_DOWEL_DEPTH = 22;
export const RAFIX_HOUSING_DIAMETER = 20;
export const RAFIX_HOUSING_DEPTH = 12.7;
export const RAFIX_MATE_DIAMETER = 5;
export const RAFIX_MATE_DEPTH = 12.7;
const RAFIX_ACCESS_DIAMETER = 8;
const BACK_PANEL_CONNECTOR_REAR_OFFSET = 8;
export const RAFIX_CENTER_FROM_EDGE = 9.5;
const RAFIX_MATE_CENTER_SHIFT = 8;
export const shouldDebugJoinery = typeof window !== 'undefined' && /^(localhost|127\.0\.0\.1)$/.test(window.location.hostname);

export function isSectionBackPanel(sourceId?: string) {
  return typeof sourceId === 'string' && sourceId.startsWith('section-back-panel:');
}

export function parseSectionBackPanelSource(sourceId?: string | null) {
  if (!isSectionBackPanel(sourceId ?? undefined)) return null;
  // section-back-panel:<tierId>:<sectionId>[:<zoneId>]
  const [, tierId, sectionId, ...zoneParts] = (sourceId ?? '').split(':');
  const zoneId = zoneParts.length > 0 ? zoneParts.join(':') : undefined;
  return tierId && sectionId ? { tierId, sectionId, zoneId } : null;
}

export function isPlinthEnabled(groupParts: Part[]) {
  return groupParts.some((part) => part.meta?.role === 'plinth-front' || part.meta?.role === 'plinth-back');
}

export function isOverlayTop(top: Part, bottom: Part) {
  return top.width > bottom.width + 0.001 || top.thickness > bottom.thickness + 0.001;
}

export function getDefaultAutoJointRules(): AutoJointRuleDraft {
  return {
    // Отступы центра пары от переднего и заднего края — стандарт производства,
    // снятый с эталона (ВМ глубиной 319): наружные отверстия встают на 69 от переда и 58 от зада.
    frontOffset: 85,
    backOffset: 74,
    shelfPinDiameter: 5,
    camDowelSpacing: 32,
  };
}

export function withGeneratedSource(part: Part, side: string, joinery: string) {
  return `${GENERATED_SOURCE_PREFIX}${part.id}:${side}:${joinery}`;
}

function isGeneratedSource(source?: string) {
  return typeof source === 'string' && source.startsWith(GENERATED_SOURCE_PREFIX);
}

export function withoutGeneratedOps(part: Part): Part {
  return {
    ...part,
    operations: part.operations.filter((op) => !isGeneratedSource(op.source)),
  };
}

function clampOffsets(depth: number, frontOffset: number, backOffset: number) {
  const front = Math.max(9, Math.min(depth - 9, frontOffset));
  const back = Math.max(front, Math.min(depth - 9, depth - backOffset));
  return [front, back] as const;
}

export function appendOps(target: Map<string, DrillOperation[]>, partId: string, ops: DrillOperation[]) {
  if (ops.length === 0) return;
  target.set(partId, [...(target.get(partId) ?? []), ...ops]);
}

export function createShelfSideSourceKey(shelfPart: Part, side: 'left' | 'right', joinery: JoineryType) {
  return withGeneratedSource(shelfPart, side, joinery);
}

export function countOpsBySource(parts: Part[], sourceKey: string) {
  return parts.reduce((count, part) => count + part.operations.filter((op) => op.source === sourceKey).length, 0);
}

export function getSupportFaceWorldX(support: SectionSupport) {
  if (support.supportFace === 'left') return support.supportPart.position.x - support.supportPart.width / 2;
  if (support.supportFace === 'right') return support.supportPart.position.x + support.supportPart.width / 2;
  return support.supportPart.position.x;
}

export function getExpectedSectionSupportPartId(
  section: CabinetSection,
  side: 'left' | 'right',
  leftSide: Part,
  rightSide: Part,
  partitionsByX: Map<string, Part>
) {
  if (side === 'left') {
    if (section.leftBoundary === 'outer') return leftSide.id;
    return partitionsByX.get(section.startX.toFixed(3))?.id ?? null;
  }
  if (section.rightBoundary === 'outer') return rightSide.id;
  return partitionsByX.get(section.endX.toFixed(3))?.id ?? null;
}

export function resolveExplicitShelfSupport(
  groupParts: Part[],
  shelfPart: Part,
  side: 'left' | 'right'
): SectionSupport | null {
  const supportPartId = side === 'left' ? shelfPart.meta?.leftSupportPartId : shelfPart.meta?.rightSupportPartId;
  if (!supportPartId) return null;
  const supportPart = groupParts.find((part) => part.id === supportPartId) ?? null;
  if (!supportPart) return null;
  return {
    supportPart,
    sectionSide: side,
    supportFace: side === 'left' ? 'right' : 'left',
  };
}

export function isValidShelfSupportAdjacency(shelfPart: Part, support: SectionSupport) {
  const role = support.supportPart.meta?.role;
  if (role !== 'left-side' && role !== 'right-side' && role !== 'partition') return false;
  const shelfFaceX = support.sectionSide === 'left'
    ? shelfPart.position.x - shelfPart.width / 2
    : shelfPart.position.x + shelfPart.width / 2;
  const supportFaceX = getSupportFaceWorldX(support);
  const xAligned = Math.abs(shelfFaceX - supportFaceX) <= 1;
  const supportMinY = support.supportPart.position.y - support.supportPart.height / 2 - 1;
  const supportMaxY = support.supportPart.position.y + support.supportPart.height / 2 + 1;
  const yAligned = shelfPart.position.y >= supportMinY && shelfPart.position.y <= supportMaxY;
  return xAligned && yAligned;
}

/**
 * Support ids in meta come from the fresh build, while a rebuild keeps the parts' old ids, so they go stale:
 * trust them only if that part really touches the end, otherwise take the side/partition the end touches.
 */
/**
 * Another shelf or local divider meets the same partition from its other face at the same height, so both joints would
 * drill the partition at the same spots. Callers shift only the panel right of the partition (see getStaggeredJointRules).
 */
export function hasMirroredHorizontalJoint(groupParts: Part[], horizontalPart: Part, support: SectionSupport) {
  const partition = support.supportPart;
  if (partition.meta?.role !== 'partition') return false;
  const otherFaceX = support.sectionSide === 'left'
    ? partition.position.x - partition.width / 2
    : partition.position.x + partition.width / 2;
  return groupParts.some((other) => (
    other.id !== horizontalPart.id
    && (other.meta?.role === 'shelf' || (other.meta?.role === 'tier-divider' && !other.meta.sourceId?.startsWith('tier-divider:')))
    && Math.abs((support.sectionSide === 'left' ? other.position.x + other.width / 2 : other.position.x - other.width / 2) - otherFaceX) < 1
    && Math.abs(other.position.y - horizontalPart.position.y) < (other.height + horizontalPart.height) / 2 + 8
  ));
}

export function findTouchingSectionSupport(groupParts: Part[], horizontalPart: Part, side: 'left' | 'right'): SectionSupport | null {
  const explicit = resolveExplicitShelfSupport(groupParts, horizontalPart, side);
  if (explicit && isValidShelfSupportAdjacency(horizontalPart, explicit)) return explicit;
  for (const supportPart of groupParts) {
    const candidate: SectionSupport = { supportPart, sectionSide: side, supportFace: side === 'left' ? 'right' : 'left' };
    if (isValidShelfSupportAdjacency(horizontalPart, candidate)) return candidate;
  }
  return null;
}

export function tagShelfAutoGeneratedOps(
  ops: DrillOperation[],
  decision: ResolvedShelfSideJoinery,
  ownerPart: Part
) {
  if (!decision.sourceKey || !decision.supportPartId || !decision.supportPartType) return ops;
  const tag: AutoGeneratedDrillMeta = {
    isAutoGenerated: true,
    ownerPartId: ownerPart.id,
    ownerPartType: ownerPart.meta?.role ?? 'panel',
    shelfId: decision.shelfId,
    side: decision.side,
    supportPartId: decision.supportPartId,
    supportPartType: decision.supportPartType,
    joineryType: decision.joinery,
    sourceKey: decision.sourceKey,
  };
  return ops.map((op) => ({ ...op, autoGenerated: tag }));
}

const TIER_DIVIDER_STAGGER = 64;
/**
 * Section back panels on both sides of one partition would be fastened at the same heights from opposite faces
 * (16 mm confirmat heads meet inside the partition): the panel to the right of the partition moves its fasteners up.
 */
export const BACK_PANEL_STAGGER = 32;

/**
 * Two joints meeting one panel from opposite faces at the same place — partitions above and below a tier divider, or
 * shelves/dividers on both sides of a partition — would drill it at the same points (12 + 12 mm into 16 mm). One of the
 * joints moves toward the middle of the depth by 64 mm (two 32-mm steps: one step would put its connector exactly onto
 * the other dowel); on shallow panels the shift shrinks so the front and back pairs don't meet.
 */
export function getStaggeredJointRules(divider: Part, rules: AutoJointRuleDraft): AutoJointRuleDraft {
  const halfSpacing = Math.max(8, rules.camDowelSpacing / 2);
  const maxOffset = divider.thickness / 2 - halfSpacing - 16;
  const shift = Math.max(0, Math.min(TIER_DIVIDER_STAGGER, maxOffset - Math.max(rules.frontOffset, rules.backOffset)));
  return { ...rules, frontOffset: rules.frontOffset + shift, backOffset: rules.backOffset + shift };
}

export function getHorizontalOffsets(part: Part, rules: AutoJointRuleDraft) {
  return clampOffsets(part.thickness, rules.frontOffset, rules.backOffset);
}

function getShelfDrillReferenceDepth(shelf: Part) {
  const value = shelf.meta?.shelfDrillReferenceDepth;
  return Number.isFinite(value) && (value ?? 0) > 0 ? (value as number) : shelf.thickness;
}

export function getShelfDepthOffsets(shelf: Part, rules: AutoJointRuleDraft, side: 'left' | 'right') {
  const minDepth = 9;
  const maxDepth = Math.max(minDepth, shelf.thickness - 9);
  const clampDepth = (value: number) => Math.max(minDepth, Math.min(maxDepth, value));
  const referenceDepth = getShelfDrillReferenceDepth(shelf);
  const frontAnchor = clampDepth(rules.frontOffset);
  const backAnchor = clampDepth(referenceDepth - rules.backOffset);
  return [frontAnchor, backAnchor]
    .map((offset) => clampDepth(offset))
    .filter((value, index, array) => array.findIndex((item) => Math.abs(item - value) < 0.001) === index);
}

export function getHorizontalSideLocalX(horizontalPart: Part, side: 'left' | 'right', offset: number) {
  const clamped = Math.max(0, Math.min(horizontalPart.thickness, offset));
  return side === 'right'
    ? Math.max(0, Math.min(horizontalPart.thickness, horizontalPart.thickness - clamped))
    : clamped;
}

export function getSupportCenterX(horizontalPart: Part, supportPart: Part) {
  return supportPart.position.x - horizontalPart.position.x + horizontalPart.width / 2;
}

export function getHorizontalCenterY(horizontalPart: Part) {
  return horizontalPart.height / 2;
}

export function getVerticalLocalY(horizontalPart: Part, supportPart: Part) {
  return supportPart.height / 2 - (horizontalPart.position.y - supportPart.position.y);
}

export function getTopSupportLocalX(horizontalPart: Part, support: SectionSupport, offset: number) {
  return support.supportFace === 'top' ? support.supportPart.width / 2 : offset;
}

export function getSupportFaceLocalX(supportPart: Part, supportFace: PartFace, offset: number) {
  if (supportFace === 'left' || supportFace === 'right') {
    return Math.max(0, Math.min(supportPart.thickness, offset));
  }
  return Math.max(0, Math.min(supportPart.width, offset));
}

export function getTopSupportLocalY(horizontalPart: Part, support: SectionSupport, offset: number) {
  return support.supportFace === 'top'
    ? offset
    : getVerticalLocalY(horizontalPart, support.supportPart);
}

export function camFaceByPartRole(part: Part): PartFace {
  return part.meta?.role === 'bottom' ? 'top' : 'bottom';
}

export function getCamCenterOffsetFromMountingEdge(width: number, sideKey: 'left' | 'right') {
  const clamped = Math.max(9, Math.min(width - 9, camCenterOffsetFromEdge));
  return sideKey === 'left' ? clamped : Math.max(9, width - clamped);
}

export function getCamCenterOffsetFromTopEdge(height: number) {
  return Math.max(9, Math.min(height - 9, camCenterOffsetFromEdge));
}

export function getCamCenterOffsetFromBottomEdge(height: number) {
  return Math.max(9, Math.min(height - 9, height - camCenterOffsetFromEdge));
}

export function getPartitionTopCamFace(horizontalPart: Part, partition: Part): 'left' | 'right' {
  return partition.position.x <= horizontalPart.position.x ? 'right' : 'left';
}

/** Same side as the top cam, so both housings of a partition open into one section. */
export function getPartitionBottomCamFace(horizontalPart: Part, partition: Part): 'left' | 'right' {
  return getPartitionTopCamFace(horizontalPart, partition);
}

function getWidthThirdOffsets(width: number) {
  const clampX = (value: number) => Math.max(24, Math.min(width - 24, value));
  return [clampX(width / 3), clampX(width * 2 / 3)] as const;
}

export function getBackPanelDistributedOffsets(span: number) {
  const clampOffset = (value: number) => Math.max(24, Math.min(span - 24, value));
  if (span > 1200) {
    return [clampOffset(span / 5), clampOffset(span / 2), clampOffset((span * 4) / 5)] as const;
  }
  return [clampOffset(span / 4), clampOffset((span * 3) / 4)] as const;
}

export function getBackPanelTopJoinery(topJoinery: ReturnType<typeof createEmptySideJoinery>, overlayTop: boolean): JoineryType {
  if (!overlayTop && (topJoinery.left === 'minifix-dowel' || topJoinery.right === 'minifix-dowel')) return 'minifix-dowel';
  if (topJoinery.left === 'confirmat' || topJoinery.right === 'confirmat') return 'confirmat';
  return 'none';
}

export function getBackPanelEdgeJoinery(backPanel: Part | null, edge: 'left' | 'right' | 'top' | 'bottom', fallback: JoineryType = 'none'): JoineryType {
  if (!backPanel) return 'none';
  // Builder back panels carry their joinery (confirmat by default), so an explicit 'none' is the user's choice.
  return backPanel.meta?.joinery?.[edge] ?? fallback;
}

export function getPartitionTopJoinery(partition: Part, plinthEnabled: boolean): JoineryType {
  const joinery = partition.meta?.joinery?.top ?? 'none';
  return joinery === 'none' ? 'none' : joinery;
}

export function getPartitionBottomJoinery(partition: Part, inherited: JoineryType): JoineryType {
  const joinery = partition.meta?.joinery?.bottom ?? 'none';
  return joinery === 'none' ? 'none' : joinery;
}

// Шаг между крепёжными точками вдоль торца, выведенный из эталона 26163: торец 325
// несёт 2 пары, 550 — три, 810 — четыре, и промежуток между центрами держится в
// пределах 190–225 мм. Точки раскладываются равномерно между передним и задним
// центром. На торце 508 эталон сам непоследователен (трижды две пары, once три),
// так что там любое правило разойдётся с частью деталей.
const CAM_DOWEL_MAX_STEP = 200;

/** Центры крепёжных пар: передний, задний и равномерно распределённые между ними. */
function getCamDowelCenters(frontCenter: number, backCenter: number) {
  const span = backCenter - frontCenter;
  if (span <= 0) return [frontCenter];
  const gaps = Math.max(1, Math.round(span / CAM_DOWEL_MAX_STEP));
  return Array.from({ length: gaps + 1 }, (_, index) => frontCenter + (span * index) / gaps);
}

export function getCamDowelPairs(depth: number, rules: AutoJointRuleDraft) {
  const [frontCenter, backCenter] = clampOffsets(depth, rules.frontOffset, rules.backOffset);
  const halfSpacing = Math.max(8, rules.camDowelSpacing / 2);
  const clampX = (value: number) => Math.max(9, Math.min(depth - 9, value));
  const detailCenter = depth / 2;
  return getCamDowelCenters(frontCenter, backCenter).map((center) => {
    const dowelTowardCenter = center <= detailCenter;
    return {
      camX: clampX(center + (dowelTowardCenter ? -halfSpacing : halfSpacing)),
      dowelX: clampX(center + (dowelTowardCenter ? halfSpacing : -halfSpacing)),
    };
  });
}

export function getShelfCamDowelPairs(shelf: Part, rules: AutoJointRuleDraft, side: 'left' | 'right') {
  const centers = getShelfDepthOffsets(shelf, rules, side);
  const halfSpacing = Math.max(8, rules.camDowelSpacing / 2);
  const clampDepth = (value: number) => Math.max(9, Math.min(shelf.thickness - 9, value));
  const depthCenter = getShelfDrillReferenceDepth(shelf) / 2;
  return centers.map((center) => {
    const dowelTowardCenter = center <= depthCenter;
    return {
      camX: clampDepth(center + (dowelTowardCenter ? -halfSpacing : halfSpacing)),
      dowelX: clampDepth(center + (dowelTowardCenter ? halfSpacing : -halfSpacing)),
    };
  });
}

export function getWorldAnchorPosition(part: Part, face: PartFace, anchor: JoineryDebugAnchor): WorldPoint {
  return getFacePointWorld(part, face, anchor);
}

export function getFaceMaxDepth(part: Part, face: PartFace) {
  switch (face) {
    case 'front':
    case 'back':
      return part.thickness;
    case 'top':
    case 'bottom':
      return part.height;
    case 'left':
    case 'right':
      return part.width;
  }
}

export function getBackPanelRearInset(backPanel: Part) {
  return Math.max(0, Math.min(backPanel.thickness, backPanel.thickness - BACK_PANEL_CONNECTOR_REAR_OFFSET));
}

/** Rafix bolt under an apron housing: mid apron thickness, like the partition-top Rafix. */
export function getApronRafixMateWorldPoint(apron: Part, x: number, y: number): WorldPoint {
  return {
    x: apron.position.x - apron.width / 2 + x,
    y,
    z: apron.position.z,
  };
}

function moveTowardCenter(value: number, center: number, distance: number) {
  return value <= center
    ? Math.min(center, value + distance)
    : Math.max(center, value - distance);
}

function createBackPanelMinifixDowelAnchor(part: Part, face: PartFace, anchor: JoineryDebugAnchor, distance: number) {
  if (face === 'top' || face === 'bottom') {
    return {
      ...anchor,
      y: moveTowardCenter(anchor.y, part.thickness / 2, distance),
    };
  }
  if (face === 'left' || face === 'right') {
    return {
      ...anchor,
      x: moveTowardCenter(anchor.x, part.thickness / 2, distance),
    };
  }
  return anchor;
}

export function shiftRafixMateTowardCenter(part: Part, face: PartFace, anchor: JoineryDebugAnchor) {
  if (face === 'top' || face === 'bottom') {
    return {
      ...anchor,
      y: Math.max(0, Math.min(part.thickness, anchor.y - RAFIX_MATE_CENTER_SHIFT)),
    };
  }
  if (face === 'left' || face === 'right') {
    return {
      ...anchor,
      x: Math.max(0, Math.min(part.thickness, anchor.x - RAFIX_MATE_CENTER_SHIFT)),
    };
  }
  return anchor;
}

export function createBackPanelRafixHousingOps(source: string, backPanel: Part, x: number, y: number) {
  return [
    createDrillOperation({
      source,
      face: 'back',
      axis: getFaceAxis('back'),
      x,
      y,
      diameter: RAFIX_HOUSING_DIAMETER,
      depth: Math.min(RAFIX_HOUSING_DEPTH, getFaceMaxDepth(backPanel, 'back')),
      through: false,
      templateName: 'Back panel Rafix housing',
      feature: 'cam-housing',
    }),
    // Access pocket is specific to back-panel Rafix only.
    // If Rafix is later added for other part pairs, do not reuse this hole by default.
    createDrillOperation({
      source,
      face: 'front',
      axis: getFaceAxis('front'),
      x,
      y,
      diameter: RAFIX_ACCESS_DIAMETER,
      depth: Math.min(4, getFaceMaxDepth(backPanel, 'front')),
      through: false,
      templateName: 'Back panel Rafix access',
      feature: 'connector-pin',
    }),
  ];
}

export function getSideInnerFaceWorldX(support: SectionSupport) {
  return support.supportFace === 'right'
    ? support.supportPart.position.x + support.supportPart.width / 2
    : support.supportPart.position.x - support.supportPart.width / 2;
}

export function debugJoineryPair(
  joineryCase: string,
  sourcePart: Part,
  targetPart: Part,
  sourceFace: PartFace,
  targetFace: PartFace,
  sourceAnchor: JoineryDebugAnchor,
  targetAnchor: JoineryDebugAnchor
) {
  if (!shouldDebugJoinery) return;
  console.debug('[joinery-debug]', {
    joineryCase,
    sourcePart: { id: sourcePart.id, name: sourcePart.name, role: sourcePart.meta?.role },
    targetPart: { id: targetPart.id, name: targetPart.name, role: targetPart.meta?.role },
    sourceFace,
    targetFace,
    sourceAnchorLocal: sourceAnchor,
    targetAnchorLocal: targetAnchor,
    sourceAnchorWorld: getWorldAnchorPosition(sourcePart, sourceFace, sourceAnchor),
    targetAnchorWorld: getWorldAnchorPosition(targetPart, targetFace, targetAnchor),
  });
}

/** A top reaching past the carcass front (top over the fronts), seen as if it ended at the carcass front: its joints are laid out on that. */
export function withoutFrontOverhang(part: Part): Part {
  const overhang = part.meta?.frontOverhang ?? 0;
  return overhang > 0
    ? { ...part, thickness: part.thickness - overhang, position: { ...part.position, z: part.position.z - overhang / 2 } }
    : part;
}

/** Moves ops laid out on `withoutFrontOverhang(part)` onto the real part: its depth coordinates count from its own front edge. */
export function shiftOpsForFrontOverhang(part: Part, ops: DrillOperation[]): DrillOperation[] {
  const overhang = part.meta?.frontOverhang ?? 0;
  if (overhang <= 0) return ops;
  return ops.map((op) => (
    op.face === 'top' || op.face === 'bottom'
      ? { ...op, y: op.y + overhang }
      : op.face === 'left' || op.face === 'right'
        ? { ...op, x: op.x + overhang }
        : op
  ));
}
