import { createId } from '../shared/ids';
import type { PartFace } from './part';

export type DrillAxis = { x: number; y: number; z: number };

export type AutoGeneratedDrillMeta = {
  isAutoGenerated: true;
  ownerPartId: string;
  ownerPartType: string;
  shelfId: string;
  side: 'left' | 'right';
  supportPartId: string;
  supportPartType: string;
  joineryType: string;
  sourceKey: string;
};

export type DrillOperation = {
  id: string;
  type: 'drill';
  source?: string;
  autoGenerated?: AutoGeneratedDrillMeta;
  feature?: 'confirmat' | 'cam-housing' | 'connector-pin' | 'dowel' | 'shelf-pin' | 'hinge-cup' | 'hinge-plate';
  face: PartFace;
  axis: DrillAxis;
  x: number;
  y: number;
  diameter: number;
  depth: number;
  through: boolean;
  templateName?: string;
};

/**
 * Паз на грани: прямой рез фрезой от (x, y) до (x2, y2) в координатах грани (face-coords.ts),
 * по центру ширины. Сейчас это паз под ХДФ задней стенки.
 */
export type GrooveOperation = {
  id: string;
  type: 'groove';
  source?: string;
  feature?: 'back-panel-groove';
  face: PartFace;
  x: number;
  y: number;
  x2: number;
  y2: number;
  width: number;
  depth: number;
  templateName?: string;
};

export type MachiningOperation = DrillOperation | GrooveOperation;

export function isDrillOperation(op: MachiningOperation): op is DrillOperation {
  return op.type === 'drill';
}

export function isGrooveOperation(op: MachiningOperation): op is GrooveOperation {
  return op.type === 'groove';
}

export function createGrooveOperation(input: Omit<GrooveOperation, 'id' | 'type'> & { id?: string }): GrooveOperation {
  return { ...input, id: input.id ?? createId('groove'), type: 'groove' };
}

export function createDrillOperation(
  input: Omit<DrillOperation, 'id' | 'type'> & { id?: string }
): DrillOperation {
  return {
    id: input.id ?? createId('drill'),
    type: 'drill',
    source: input.source ?? 'manual',
    autoGenerated: input.autoGenerated,
    feature: input.feature,
    face: input.face,
    axis: input.axis,
    x: input.x,
    y: input.y,
    diameter: input.diameter,
    depth: input.depth,
    through: input.through,
    templateName: input.templateName,
  };
}

export function getFaceAxis(face: PartFace): DrillAxis {
  switch (face) {
    case 'front': return { x: 0, y: 0, z: -1 };
    case 'back': return { x: 0, y: 0, z: 1 };
    case 'top': return { x: 0, y: -1, z: 0 };
    case 'bottom': return { x: 0, y: 1, z: 0 };
    case 'left': return { x: 1, y: 0, z: 0 };
    case 'right': return { x: -1, y: 0, z: 0 };
  }
}
