import { createId } from '../shared/ids';
import type { PartFace } from './part';

export type DrillAxis = { x: number; y: number; z: number };

export type AutoGeneratedDrillMeta = {
  isAutoGenerated: true;
  ownerPartId: string;
  ownerPartType: string;
  shelfId: string;
  side: 'left' | 'right';
  supportPartId: string;
  supportPartType: string;
  joineryType: string;
  sourceKey: string;
};

export type DrillOperation = {
  id: string;
  type: 'drill';
  source?: string;
  autoGenerated?: AutoGeneratedDrillMeta;
  feature?: 'confirmat' | 'cam-housing' | 'connector-pin' | 'dowel' | 'shelf-pin' | 'hinge-cup' | 'hinge-plate';
  face: PartFace;
  axis: DrillAxis;
  x: number;
  y: number;
  diameter: number;
  depth: number;
  through: boolean;
  templateName?: string;
};

export type MachiningOperation = DrillOperation;

export function createDrillOperation(
  input: Omit<DrillOperation, 'id' | 'type'> & { id?: string }
): DrillOperation {
  return {
    id: input.id ?? createId('drill'),
    type: 'drill',
    source: input.source ?? 'manual',
    autoGenerated: input.autoGenerated,
    feature: input.feature,
    face: input.face,
    axis: input.axis,
    x: input.x,
    y: input.y,
    diameter: input.diameter,
    depth: input.depth,
    through: input.through,
    templateName: input.templateName,
  };
}

export function getFaceAxis(face: PartFace): DrillAxis {
  switch (face) {
    case 'front': return { x: 0, y: 0, z: -1 };
    case 'back': return { x: 0, y: 0, z: 1 };
    case 'top': return { x: 0, y: -1, z: 0 };
    case 'bottom': return { x: 0, y: 1, z: 0 };
    case 'left': return { x: 1, y: 0, z: 0 };
    case 'right': return { x: -1, y: 0, z: 0 };
  }
}
